deployment:
  version: IMAGE_VERSION
  imageURL: 315069654700.dkr.ecr.us-east-1.amazonaws.com/expense/frontend
hpa:
  utilisation: 5
tgb:
  arn: arn:aws:elasticloadbalancing:us-east-1:315069654700:targetgroup/expense-dev/fbb46f1746ee857e
